In [116]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [177]:
df = pd.read_csv("train_data.csv")
dff = pd.read_csv("test_data.csv")
ss = pd.read_csv("SampleSubmission.csv")



In [118]:
df.shape

(7160, 14)

In [119]:
dff.shape

(3069, 13)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer Id         7160 non-null   object 
 1   YearOfObservation   7160 non-null   int64  
 2   Insured_Period      7160 non-null   float64
 3   Residential         7160 non-null   int64  
 4   Building_Painted    7160 non-null   object 
 5   Building_Fenced     7160 non-null   object 
 6   Garden              7153 non-null   object 
 7   Settlement          7160 non-null   object 
 8   Building Dimension  7054 non-null   float64
 9   Building_Type       7160 non-null   int64  
 10  Date_of_Occupancy   6652 non-null   float64
 11  NumberOfWindows     7160 non-null   object 
 12  Geo_Code            7058 non-null   object 
 13  Claim               7160 non-null   int64  
dtypes: float64(3), int64(4), object(7)
memory usage: 783.2+ KB


In [121]:
df.isna().sum()

Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Garden                  7
Settlement              0
Building Dimension    106
Building_Type           0
Date_of_Occupancy     508
NumberOfWindows         0
Geo_Code              102
Claim                   0
dtype: int64

In [122]:
df.Garden.value_counts()

O    3602
V    3551
Name: Garden, dtype: int64

In [123]:
df.Garden = df.Garden.fillna(value='O')

In [124]:
df.Garden.isna().sum()

0

In [125]:
building_mean = np.mean(df["Building Dimension"])

In [126]:
building_mean

1883.7275304791608

In [127]:
df["Building Dimension"] = df["Building Dimension"].fillna(value = 1883.7275304791608)

In [128]:
df["Building Dimension"].isna().sum()

0

In [129]:
date_mean = np.mean(df["Date_of_Occupancy"])

In [130]:
date_mean

1964.456404088996

In [131]:
df["Date_of_Occupancy"] = df["Date_of_Occupancy"].fillna(value = 1964.456404088996)

In [132]:
df["Date_of_Occupancy"].isna().sum()

0

In [133]:
df["Geo_Code"].value_counts()

6088     143
33063    137
6083     113
13206     98
31555     87
        ... 
59650      1
59656      1
60057      1
60172      1
2B353      1
Name: Geo_Code, Length: 1307, dtype: int64

In [134]:
df["Geo_Code"] = df["Geo_Code"].fillna(value= '6088')

In [135]:
df["Geo_Code"].isna().sum()

0

In [136]:
df.isna().sum()

Customer Id           0
YearOfObservation     0
Insured_Period        0
Residential           0
Building_Painted      0
Building_Fenced       0
Garden                0
Settlement            0
Building Dimension    0
Building_Type         0
Date_of_Occupancy     0
NumberOfWindows       0
Geo_Code              0
Claim                 0
dtype: int64

In [137]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer Id         3069 non-null   object 
 1   YearOfObservation   3069 non-null   int64  
 2   Insured_Period      3069 non-null   float64
 3   Residential         3069 non-null   int64  
 4   Building_Painted    3069 non-null   object 
 5   Building_Fenced     3069 non-null   object 
 6   Garden              3065 non-null   object 
 7   Settlement          3069 non-null   object 
 8   Building Dimension  3056 non-null   float64
 9   Building_Type       3069 non-null   int64  
 10  Date_of_Occupancy   2341 non-null   float64
 11  NumberOfWindows     3069 non-null   object 
 12  Geo_Code            3056 non-null   object 
dtypes: float64(3), int64(3), object(7)
memory usage: 311.8+ KB


In [138]:
dff.isna().sum()

Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Garden                  4
Settlement              0
Building Dimension     13
Building_Type           0
Date_of_Occupancy     728
NumberOfWindows         0
Geo_Code               13
dtype: int64

In [139]:
dff.Garden.value_counts()

V    2240
O     825
Name: Garden, dtype: int64

In [140]:
dff.Garden = dff.Garden.fillna(value='V')

In [141]:
building_mean1 = np.mean(dff["Building Dimension"])

In [142]:
building_mean1

1666.7905759162304

In [143]:
dff["Building Dimension"] = dff["Building Dimension"].fillna(value = 1666.7905759162304)

In [144]:
date_mean1 = np.mean(dff["Date_of_Occupancy"])

In [145]:
date_mean1

1966.7817172148655

In [146]:
dff["Date_of_Occupancy"] = dff["Date_of_Occupancy"].fillna(value = 1966.7817172148655)

In [147]:
dff["Geo_Code"].value_counts()

6083     113
6088      95
2B033     74
13206     68
13204     61
        ... 
68149      1
29058      1
68062      1
68060      1
74081      1
Name: Geo_Code, Length: 697, dtype: int64

In [148]:
dff["Geo_Code"] = dff["Geo_Code"].fillna(value= '6083')

In [149]:
dff.isna().sum()

Customer Id           0
YearOfObservation     0
Insured_Period        0
Residential           0
Building_Painted      0
Building_Fenced       0
Garden                0
Settlement            0
Building Dimension    0
Building_Type         0
Date_of_Occupancy     0
NumberOfWindows       0
Geo_Code              0
dtype: int64

In [150]:
df.drop("Customer Id", axis = 1, inplace = True)

In [151]:
dff.drop("Customer Id", axis = 1, inplace = True)

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   YearOfObservation   7160 non-null   int64  
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64  
 3   Building_Painted    7160 non-null   object 
 4   Building_Fenced     7160 non-null   object 
 5   Garden              7160 non-null   object 
 6   Settlement          7160 non-null   object 
 7   Building Dimension  7160 non-null   float64
 8   Building_Type       7160 non-null   int64  
 9   Date_of_Occupancy   7160 non-null   float64
 10  NumberOfWindows     7160 non-null   object 
 11  Geo_Code            7160 non-null   object 
 12  Claim               7160 non-null   int64  
dtypes: float64(3), int64(4), object(6)
memory usage: 727.3+ KB


In [153]:
lab_enc = LabelEncoder()
df["Building_Painted"] = lab_enc.fit_transform(df["Building_Painted"])
df["Building_Fenced"] = lab_enc.fit_transform(df["Building_Fenced"])
df["Garden"] = lab_enc.fit_transform(df["Garden"])
df["Settlement"] = lab_enc.fit_transform(df["Settlement"])
df["NumberOfWindows"] = lab_enc.fit_transform(df["NumberOfWindows"])
df["Geo_Code"] = lab_enc.fit_transform(df["Geo_Code"])



dff["Building_Painted"] = lab_enc.fit_transform(dff["Building_Painted"])
dff["Building_Fenced"] = lab_enc.fit_transform(dff["Building_Fenced"])
dff["Garden"] = lab_enc.fit_transform(dff["Garden"])
dff["Settlement"] = lab_enc.fit_transform(dff["Settlement"])
dff["NumberOfWindows"] = lab_enc.fit_transform(dff["NumberOfWindows"])
dff["Geo_Code"] = lab_enc.fit_transform(dff["Geo_Code"])




In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   YearOfObservation   7160 non-null   int64  
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64  
 3   Building_Painted    7160 non-null   int32  
 4   Building_Fenced     7160 non-null   int32  
 5   Garden              7160 non-null   int32  
 6   Settlement          7160 non-null   int32  
 7   Building Dimension  7160 non-null   float64
 8   Building_Type       7160 non-null   int64  
 9   Date_of_Occupancy   7160 non-null   float64
 10  NumberOfWindows     7160 non-null   int32  
 11  Geo_Code            7160 non-null   int32  
 12  Claim               7160 non-null   int64  
dtypes: float64(3), int32(6), int64(4)
memory usage: 559.5 KB


In [155]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   YearOfObservation   3069 non-null   int64  
 1   Insured_Period      3069 non-null   float64
 2   Residential         3069 non-null   int64  
 3   Building_Painted    3069 non-null   int32  
 4   Building_Fenced     3069 non-null   int32  
 5   Garden              3069 non-null   int32  
 6   Settlement          3069 non-null   int32  
 7   Building Dimension  3069 non-null   float64
 8   Building_Type       3069 non-null   int64  
 9   Date_of_Occupancy   3069 non-null   float64
 10  NumberOfWindows     3069 non-null   int32  
 11  Geo_Code            3069 non-null   int32  
dtypes: float64(3), int32(6), int64(3)
memory usage: 215.9 KB


In [156]:
X = df.drop("Claim", axis = 1)
y = df.Claim
test = dff

In [157]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 120)

In [158]:
X_train.shape

(5728, 12)

In [159]:
X_test.shape

(1432, 12)

In [160]:
y_train.shape

(5728,)

In [161]:
y_test.shape

(1432,)

In [162]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, f1_score
linear = LinearRegression()
linear.fit(X_train, y_train)

LinearRegression()

In [163]:
linear_predict = linear.predict(X_test)

In [164]:
linear_predict

array([0.33505043, 0.0848828 , 0.12521046, ..., 0.03433311, 0.10068199,
       0.07357787])

In [165]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
log_pred = logistic.predict(X_test)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [166]:
accuracy_score(y_test, log_pred)

0.7751396648044693

In [167]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor()
tree.fit(X_train, y_train)
tree_pred = tree.predict(X_test)

In [168]:
from sklearn.naive_bayes import GaussianNB

naivemodel = GaussianNB()

naivemodel.fit(X_train, y_train)
na_pred = naivemodel.predict(X_test)
na_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [169]:
accuracy_score(y_test, na_pred)

0.763268156424581

In [170]:
# for SVM model
from sklearn.svm import SVC
SVMmodel = SVC()
SVMmodel.fit(X_train, y_train)
SVM_pred = SVMmodel.predict(X_test)
# f1_score(y_test, SVM_pred) * 100
accuracy_score(y_test, SVM_pred)

0.7737430167597765

In [171]:
# For random forest model
from sklearn.ensemble import RandomForestClassifier
randomforestmodel = RandomForestClassifier()
randomforestmodel.fit(X_train, y_train)
ran_pred = randomforestmodel.predict(X_test)
# f1_score(y_test, ran_pred)*100
accuracy_score(y_test, ran_pred)


0.7688547486033519

# SINCE LOGISTIC REGRESSION GAVE THE BEST ACCURACY SCORE 

In [172]:
prediction = logistic.predict(test)

In [173]:
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [182]:
# new_ss["Claim"] = prediction

a = {'Customer Id': dff["Customer Id"], 'Claim': prediction}   #to merge a column 
result = pd.DataFrame(data = a)
# ss.to_csv('result.csv', index = False)

In [183]:
result.to_csv('finalresult.csv',index= False)